spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_data_jpa_db?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true
      format_sql: true
